data:
  manifest_train: manifests/train.csv
  manifest_val: manifests/val.csv
  manifest_test: manifests/test.csv
  manifest_stride: 8
  image_col: image_path
  presence_col: presence
  cx_col: cx
  cy_col: cy
  use_pre_letterboxed: true
  letterbox_meta_csv: manifests/letterbox_meta.csv
  letterbox_size_assert: 224
train:
  image_size: 224
  batch_size: 40
  num_workers: 40
  dataloader_timeout_s: 160
  persistent_workers: true
  freeze_bn_running_stats: false
  epochs: 100
  lr: 0.001
  weight_decay: 1.0e-05
  amp: true
  scale_lr_by_world_size: true
  seed: 493
  save_dir: outputs/runs/exp_31_energy-presence_LR
  val_every: 1
  best_ckpt_start_epoch: 1
  backbone: x3d_m
  backbone_pretrained: true
  heatmap_stride: 2
  use_aug: false
  temporal_T: 16
  temporal_stride: 1
  presence_dropout: 0.5
  presence_from_peak: false
  presence_mode: energy
  presence_topk: 50
loss:
  heatmap_sigma_px: 8.0
  heatmap_loss: dsnt
  heatmap_focal_alpha: 1.7
  heatmap_focal_beta: 3.0
  dsnt_tau: 0.8
  dsnt_coord_loss: l1
  peak_mode: energy
  peak_pool: logsumexp
  peak_tau: 1.0
  peak_logit_alpha: 0.5
  peak_logit_center: logk+median
  energy_init_b0: 0.0
  energy_init_wE: 1.0
  energy_init_wC: 1.0
  energy_init_wH: 0.4
  w_heatmap_focal_reg: 1.0
  heatmap_focal_reg_neg_multiplier: 0.9
  w_heatmap: 1.0
  w_presence: 1.0
  w_peak_bce: 1.5
  heatmap_neg_multiplier: 1.0
  heatmap_pos_multiplier: 1.0
  presence_loss: bce
  presence_focal_gamma: 2.2
  presence_focal_alpha: 0.9
  auto_balance: false
  auto_balance_clip:
  - 0.1
  - 100.0
  presence_label_smoothing: 0.0
infer:
  batch_size: 40
  freeze_bn_running_stats: false
  presence_from_peak: true
  presence_mode: energy
  peak_threshold: 0.5
  peak_pool: logsumexp
  peak_tau: 1.15
  presence_threshold: 0.5
  center_tau: 1.0
  topk_peaks: 1
  roi_base_radius_px: 112
  roi_sigma_multiplier: 2.5
  out_dir: outputs/preds
